### ISSUE TITLE
Bugs 3 callback

### ISSUE THREAD

**Issue by goebish** [DeviationTX/deviation#738]
https://github.com/DeviationTX/deviation/blob/0a5592c4dd2870f94bf56152f0ee91c0a63ef1be/src/protocol/bugs3_a7105.c#L644
Is this line useless or is it a bug?

**Comment by hexfet** [comment]
I think neither.  If the count expires without completion, then return to the same state in 500us and again check if the operation is complete.  Contrast to hubsan_a7105.c line 501 where the code just continues as if completed.

It's arguable whether it would actually work if the operation is not complete on first try since the overall timing would be affected.

**Comment by goebish** [comment]
The break exits the while loop, not the switch, packet_period is then set to DELAY_WAIT_RX

**Comment by hexfet** [comment]
I see, good catch.  Same at line 579.  It could either be removed, or return instead of break.  Or remove the loop completely.  I can check if completion test ever fails.
